version: '3.8'

services:
  fashion-service:
    build:
      context: .
      dockerfile: Dockerfile.fashion
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    environment:
      - PORT=8002
    command: uvicorn main_fashion:app --host 0.0.0.0 --port 8002 --reload

  batik-service:
    build:
      context: .
      dockerfile: Dockerfile.batik
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - torch_cache:/root/.cache/torch
    environment:
      - PORT=8001
    command: uvicorn main_batik:app --host 0.0.0.0 --port 8001 --reload

volumes:
  torch_cache:
